### ISSUE TITLE
Mapa mental web3.0

### ISSUE THREAD

**Issue by saul19bautista** [SistemasTecTlaxiaco/actividad-4-mapa-mental-web-3-saul19bautista#1]
![Saul_Mapa mental](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-web-3-saul19bautista/assets/90206458/4327a1e3-370c-4827-aac3-02f37d08dc9e)

**Comment by isairey** [comment]
Identificacion del tema: 4
Contenidos: 4
Organizacion y estructura: 4
Formato: 4
Difusion: 4
Calificacion:  20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
